name = "HybridQSim"
uuid = "bf432aaa-5ba2-4e4c-ac44-0d82221f9ace"
version = "0.1.0"
authors = ["Yingkang Cao <cyngkng@gmail.com>"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
QuantumToolbox = "6c2fb7c5-b903-41d2-bc5e-5a7c320b9fab"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
CairoMakie = "0.15.7"
QuantumToolbox = "0.39.1"
StaticArrays = "1.9.15"
