name = "HybridQSim"
uuid = "bf432aaa-5ba2-4e4c-ac44-0d82221f9ace"
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
QuantumToolbox = "6c2fb7c5-b903-41d2-bc5e-5a7c320b9fab"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CairoMakie = "0.15.7"
QuantumToolbox = "0.39.1"
Random = "1.11.0"
StaticArrays = "1.9.15"
Statistics = "1.11.1"
